Global:
  debug: false
  use_gpu: false
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_simple
  save_epoch_step: 10
  eval_batch_step: [0, 500]
  cal_metric_during_train: true
  pretrained_model:  
  checkpoints:  
  save_inference_dir: 
  use_visualdl: false
  infer_img:  
  character_dict_path: ./dataset/dict. txt
  max_text_length: 25
  infer_mode: false
  use_space_char: false
  distributed: false
  save_res_path: ./output/rec_simple/predicts. txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr: 
    name:  Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone: 
    name: MobileNetV3
    scale: 0.5
    model_name: small
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name:  CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator:  acc

Train:
  dataset: 
    name: SimpleDataSet
    data_dir: ./dataset/train/
    label_file_list:
      - ./dataset/train/train_list.txt
    transforms:
      - DecodeImage:
          img_mode:  BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape:  [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: true
    batch_size_per_card: 32
    drop_last: true
    num_workers: 0
    use_shared_memory: false

Eval:
  dataset: 
    name: SimpleDataSet
    data_dir: ./dataset/val/
    label_file_list:
      - ./dataset/val/val_list.txt
    transforms:
      - DecodeImage:
          img_mode:  BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape:  [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 32
    num_workers: 0
    use_shared_memory: false
